// ----------------------------------------------------------------------------
// This file was auto-generated by `bun run env`.
// Do not edit this file directly.
// To add a new environment variable:
// 1. Add it to `.env.template`
// 2. Run `bun run env`
// ----------------------------------------------------------------------------

import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
	/**
	 * Specify what environment variables are available on the server.
	 */
	server: {
		POSTGRES_USER: z.string().min(1),
		POSTGRES_PASSWORD: z.string().min(1),
		POSTGRES_DB: z.string().min(1),
		POSTGRES_PORT: z.coerce.number(),
		PGBOUNCER_PORT: z.coerce.number(),
		REDIS_PASSWORD: z.string().min(1),
		REDIS_PORT: z.coerce.number(),
		DATABASE_URL: z.string().url(),
		DIRECT_DATABASE_URL: z.string().url(),
		REDIS_URL: z.string().url(),
		BETTER_AUTH_SECRET: z.string().min(1),
		BETTER_AUTH_URL: z.string().url(),
	},

	/**
	 * Destructure all variables from `process.env` to make sure they aren't client-only.
	 */
	runtimeEnv: {
		POSTGRES_USER: process.env.POSTGRES_USER,
		POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
		POSTGRES_DB: process.env.POSTGRES_DB,
		POSTGRES_PORT: process.env.POSTGRES_PORT,
		PGBOUNCER_PORT: process.env.PGBOUNCER_PORT,
		REDIS_PASSWORD: process.env.REDIS_PASSWORD,
		REDIS_PORT: process.env.REDIS_PORT,
		DATABASE_URL: process.env.DATABASE_URL,
		DIRECT_DATABASE_URL: process.env.DIRECT_DATABASE_URL,
		REDIS_URL: process.env.REDIS_URL,
		BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
		BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
	},

	/**
	 * Run `build` or `dev` with `SKIP_ENV_VALIDATION` to skip env validation.
	 * This is especially useful for Docker builds.
	 */
	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
});
