// ----------------------------------------------------------------------------
// This file was auto-generated by `pnpm run syncEnv` from the root.
// Do not edit this file directly.
// To add a new environment variable:
// 1. Add it to `.env.template`
// 2. Run `pnpm run syncEnv`
// ----------------------------------------------------------------------------

import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
	/**
	 * Specify what environment variables are available on the server.
	 */
	server: {

	},

	/**
	 * Specify what environment variables are available on the client.
	 */
	clientPrefix: "VITE_",
	client: {
		VITE_APP_NAME: z.string().min(1),
		VITE_API_URL: z.string().url(),
	},

	/**
	 * Destructure all variables to make sure they aren't client-only.
	 */
	runtimeEnv: {
		VITE_APP_NAME: import.meta.env.VITE_APP_NAME,
		VITE_API_URL: import.meta.env.VITE_API_URL,
	},

	/**
	 * Run `build` or `dev` with `SKIP_ENV_VALIDATION` to skip env validation.
	 * This is especially useful for Docker builds.
	 */
	skipValidation: !!import.meta.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
});
