import { join } from "node:path";
import { parse } from "dotenv";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const rootDir = process.cwd();

const apps = [
	{
		name: "API",
		dir: join(rootDir, "apps", "api"),
		envTsPath: join(rootDir, "apps", "api", "src", "config", "env.ts"),
		clientPrefix: null,
	},
	{
		name: "Dashboard",
		dir: join(rootDir, "apps", "dashboard"),
		envTsPath: join(rootDir, "apps", "dashboard", "app", "config", "env.ts"),
		clientPrefix: "VITE_",
	},
];

async function syncEnvForApp(app: typeof apps[0]) {
	const envPath = join(app.dir, ".env");
	const envTemplatePath = join(app.dir, ".env.template");

	console.log(`\n🔄 Syncing .env with .env.template format for ${app.name}...`);

	if (!existsSync(envTemplatePath)) {
		console.warn(`⚠️ .env.template not found in ${app.name}. Skipping sync.`);
		return;
	}

	const templateContent = readFileSync(envTemplatePath, "utf-8");
	const templateVars = parse(templateContent);

	let currentEnvContent = "";
	let currentVars: Record<string, string> = {};

	if (existsSync(envPath)) {
		currentEnvContent = readFileSync(envPath, "utf-8");
		currentVars = parse(currentEnvContent);
	}

	let appended = false;
	let newEnvContent = currentEnvContent;

	if (newEnvContent && !newEnvContent.endsWith("\n")) {
		newEnvContent += "\n";
	}

	for (const [key, value] of Object.entries(templateVars)) {
		if (!(key in currentVars)) {
			console.log(`➕ Adding missing variable: ${key}`);
			// Only wrap in quotes if it contains spaces or special characters
			const needsQuotes =
				/[\s="']/.test(value) &&
				!value.startsWith('"') &&
				!value.startsWith("'");
			const formattedValue = needsQuotes
				? `"${value.replace(/"/g, '\\"')}"`
				: value;
			newEnvContent += `${key}=${formattedValue}\n`;
			appended = true;
		}
	}

	if (appended) {
		writeFileSync(envPath, newEnvContent, "utf-8");
		console.log(`✅ .env synchronized successfully in ${app.name}.`);
	} else {
		console.log(`✅ .env is already up to date in ${app.name}.`);
	}
}

async function generateEnvTsForApp(app: typeof apps[0]) {
	console.log(`🏭 Generating env.ts schema for ${app.name}...`);

	const envTemplatePath = join(app.dir, ".env.template");

	if (!existsSync(envTemplatePath)) {
		console.warn(`⚠️ .env.template not found in ${app.name}. Cannot generate env.ts schema.`);
		return;
	}

	const templateContent = readFileSync(envTemplatePath, "utf-8");
	const templateVars = parse(templateContent);
	const isDashboard = app.name === "Dashboard";

	const clientVars: string[] = [];
	const serverVars: string[] = [];
	const runtimeEnv: string[] = [];

	for (const [key, value] of Object.entries(templateVars)) {
		// Determine the zod type
		let zodTypeStr = "z.string().min(1)";
		const valTrimmed = value.trim();

		if (valTrimmed === "true" || valTrimmed === "false") {
			zodTypeStr = 'z.string().transform((s) => s === "true")';
		} else if (!Number.isNaN(Number(valTrimmed)) && valTrimmed !== "") {
			zodTypeStr = "z.coerce.number()";
		} else if (
			key.endsWith("_URL") ||
			valTrimmed.startsWith("http://") ||
			valTrimmed.startsWith("https://") ||
			valTrimmed.startsWith("redis://") ||
			valTrimmed.startsWith("postgresql://")
		) {
			zodTypeStr = "z.string().url()";
		}

		if (app.clientPrefix && key.startsWith(app.clientPrefix)) {
			clientVars.push(`\t\t${key}: ${zodTypeStr},`);
			// In Vite/React-Router, client variables are accessed via import.meta.env
			runtimeEnv.push(`\t\t${key}: import.meta.env.${key},`);
		} else {
			serverVars.push(`\t\t${key}: ${zodTypeStr},`);
			// Server variables can be accessed on process.env in Node
			runtimeEnv.push(`\t\t${key}: process.env.${key},`);
		}
	}

	const hasClientEnv = clientVars.length > 0;

	const generatedCode = `// ----------------------------------------------------------------------------
// This file was auto-generated by \`pnpm run syncEnv\` from the root.
// Do not edit this file directly.
// To add a new environment variable:
// 1. Add it to \`.env.template\`
// 2. Run \`pnpm run syncEnv\`
// ----------------------------------------------------------------------------

import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
	/**
	 * Specify what environment variables are available on the server.
	 */
	server: {
${serverVars.join("\n")}
	},
${hasClientEnv ? `
	/**
	 * Specify what environment variables are available on the client.
	 */
	clientPrefix: "${app.clientPrefix}",
	client: {
${clientVars.join("\n")}
	},` : ""}

	/**
	 * Destructure all variables to make sure they aren't client-only.
	 */
	runtimeEnv: {
${runtimeEnv.join("\n")}
	},

	/**
	 * Run \`build\` or \`dev\` with \`SKIP_ENV_VALIDATION\` to skip env validation.
	 * This is especially useful for Docker builds.
	 */
	skipValidation: ${isDashboard ? "!!import.meta.env.SKIP_ENV_VALIDATION" : "!!process.env.SKIP_ENV_VALIDATION"},
	emptyStringAsUndefined: true,
});
`;

	writeFileSync(app.envTsPath, generatedCode, "utf-8");
	console.log(`✅ env.ts schema generated successfully for ${app.name}.`);
}

async function run() {
	for (const app of apps) {
		await syncEnvForApp(app);
		await generateEnvTsForApp(app);
	}
}

run().catch((error) => {
	console.error("❌ Failed to sync environments:", error);
	process.exit(1);
});
