import { join } from "node:path";
import { parse } from "dotenv";

const apiDir = join(import.meta.dir, "..");
const envPath = join(apiDir, ".env");
const envTemplatePath = join(apiDir, ".env.template");
const envTsPath = join(apiDir, "src", "config", "env.ts");

async function syncEnv() {
	console.log("🔄 Syncing .env with .env.template...");

	const templateFile = Bun.file(envTemplatePath);
	if (!(await templateFile.exists())) {
		console.warn("⚠️ .env.template not found. Skipping sync.");
		return;
	}

	const templateContent = await templateFile.text();
	const templateVars = parse(templateContent);

	let currentEnvContent = "";
	let currentVars: Record<string, string> = {};

	const envFile = Bun.file(envPath);
	if (await envFile.exists()) {
		currentEnvContent = await envFile.text();
		currentVars = parse(currentEnvContent);
	}

	let appended = false;
	let newEnvContent = currentEnvContent;

	if (newEnvContent && !newEnvContent.endsWith("\n")) {
		newEnvContent += "\n";
	}

	for (const [key, value] of Object.entries(templateVars)) {
		if (!(key in currentVars)) {
			console.log(`➕ Adding missing variable: ${key}`);
			// Only wrap in quotes if it contains spaces or special characters
			const needsQuotes =
				/[\s="']/.test(value) &&
				!value.startsWith('"') &&
				!value.startsWith("'");
			const formattedValue = needsQuotes
				? `"${value.replace(/"/g, '\\"')}"`
				: value;
			newEnvContent += `${key}=${formattedValue}\n`;
			appended = true;
		}
	}

	if (appended) {
		await Bun.write(envPath, newEnvContent);
		console.log("✅ .env synchronized successfully.");
	} else {
		console.log("✅ .env is already up to date.");
	}
}

async function generateEnvTs() {
	console.log("🏭 Generating src/env.ts...");

	const templateFile = Bun.file(envTemplatePath);
	if (!(await templateFile.exists())) {
		console.error("❌ .env.template not found. Cannot generate env.ts.");
		process.exit(1);
	}

	const templateContent = await templateFile.text();
	const templateVars = parse(templateContent);

	const serverVars: string[] = [];
	const runtimeEnv: string[] = [];

	for (const [key, value] of Object.entries(templateVars)) {
		// Determine the zod type
		let zodTypeStr = "z.string().min(1)";
		const valTrimmed = value.trim();

		if (valTrimmed === "true" || valTrimmed === "false") {
			// transform "true"/"false" string to boolean for env vars
			zodTypeStr = 'z.string().transform((s) => s === "true")';
		} else if (!Number.isNaN(Number(valTrimmed)) && valTrimmed !== "") {
			zodTypeStr = "z.coerce.number()";
		} else if (
			key.endsWith("_URL") ||
			valTrimmed.startsWith("http://") ||
			valTrimmed.startsWith("https://") ||
			valTrimmed.startsWith("redis://") ||
			valTrimmed.startsWith("postgresql://")
		) {
			zodTypeStr = "z.string().url()";
		}

		serverVars.push(`\t\t${key}: ${zodTypeStr},`);
		runtimeEnv.push(`\t\t${key}: process.env.${key},`);
	}

	const generatedCode = `// ----------------------------------------------------------------------------
// This file was auto-generated by \`bun run env\`.
// Do not edit this file directly.
// To add a new environment variable:
// 1. Add it to \`.env.template\`
// 2. Run \`bun run env\`
// ----------------------------------------------------------------------------

import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
	/**
	 * Specify what environment variables are available on the server.
	 */
	server: {
${serverVars.join("\n")}
	},

	/**
	 * Destructure all variables from \`process.env\` to make sure they aren't client-only.
	 */
	runtimeEnv: {
${runtimeEnv.join("\n")}
	},

	/**
	 * Run \`build\` or \`dev\` with \`SKIP_ENV_VALIDATION\` to skip env validation.
	 * This is especially useful for Docker builds.
	 */
	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
});
`;

	await Bun.write(envTsPath, generatedCode);
	console.log("✅ src/env.ts generated successfully.");
}

// Execute both tasks
await syncEnv();
await generateEnvTs();
